name: Release // Node.js Package

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Package
        run: |
          cd backend/nodejs
          npm install
          npm pack
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aiphsd-node-package
          path: backend/nodejs/*.tgz
