name: Release // Python Package

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install build tools
        run: pip install build setuptools wheel
      - name: Build Package
        run: |
          cd backend/python
          python -m build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aiphsd-python-package
          path: backend/python/dist/*
